name: API Sisyphus CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install HTML Validator
        run: npm install -g html-validate

      - name: Run Syntax & Accessibility Checks

        run: html-validate index.html
